export const data = [{
  file: 'https://commons.wikimedia.org/entity/M95796206', fileLabel: 'Villa Marta in Jurmala, Latvia', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Villa_Marta_in_Jurmala.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Villa_Marta_in_Jurmala.jpg', encoding: 'image/jpeg', creator: 'Igors Cernovs', depictIDs: 'Q80510;Q178382;Q13460939;Q3950;Q12271;Q211', depictLabels: 'Alla Pugacheva;Jūrmala;Q13460939;villa;architecture;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M92767065', fileLabel: 'M92767065', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Sala_Adamovas_ezera_dabas_parkā.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Sala_Adamovas_ezera_dabas_parkā.jpg', encoding: 'image/jpeg', creator: 'Karlisjm', depictIDs: 'Q208113;Q16350289;Q21002218;Q211', depictLabels: 'Latgale;Adamovas ezers;Adamova Lake Nature Park;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M92767151', fileLabel: 'M92767151', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Rāznas_ezers.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Rāznas_ezers.jpg', encoding: 'image/jpeg', creator: 'Karlisjm', depictIDs: 'Q208113;Q503021;Q549295;Q603462;Q211', depictLabels: 'Latgale;Natura 2000;Rāzna National Park;Lake Razna;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M92749108', fileLabel: 'M92749108', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Barkavas_ozoli.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Barkavas_ozoli.jpg', encoding: 'image/jpeg', creator: 'Karlisjm', depictIDs: 'Q503021;Q2884591;Q10965030;Q165145;Q211', depictLabels: 'Natura 2000;Barkava Parish;Barkavas ozolu audze;Quercus robur;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M97971375', fileLabel: 'M97971375', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Zilaiskalns_1960+.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Zilaiskalns_1960+.jpg', encoding: 'image/jpeg', creator: 'Janisjanis2020', depictIDs: 'Q745303;Q8071878;Q15220099;Q211', depictLabels: 'Vidzeme;Zilaiskalns Parish;Zilaiskalns;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M99011756', fileLabel: 'Latvian long-term residence permit ID card (2021 design)', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Pastāvīgās_uzturēšanās_atļauja_LV.gif200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Pastāvīgās_uzturēšanās_atļauja_LV.gif', encoding: 'image/gif', depictIDs: 'Q23012016;Q211', depictLabels: 'Office of Citizenship and Migration Affairs;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M99011754', fileLabel: 'Latvian short-term residence permit ID card (2021 design)', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Uzturēšanās_atļauja_LV.gif200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Uzturēšanās_atļauja_LV.gif', encoding: 'image/gif', depictIDs: 'Q23012016;Q211', depictLabels: 'Office of Citizenship and Migration Affairs;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M103770429', fileLabel: 'The shape of Latvia with the Soviet flag on it.', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/LatviawithSovietFlagMap.svg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/LatviawithSovietFlagMap.svg', encoding: 'image/svg+xml', creator: 'CheeseMilkYogurt', depictIDs: 'Q211', depictLabels: 'Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M81608990', fileLabel: 'M81608990', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Baltic_Way_in_Latvia_between_Cēsis_and_Valmiera.jpeg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Baltic_Way_in_Latvia_between_Cēsis_and_Valmiera.jpeg', encoding: 'image/jpeg', depictIDs: 'Q83620;Q389646;Q1562095;Q1986098;Q2425;Q211', depictLabels: 'thoroughfare;Baltic Way;human chain;standing;1989;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M54809385', fileLabel: 'M54809385', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Irbes_ligzda_pie_Vecdorvalka,_Dundagas_pagasts,_Dundagas_novads,_Latvia_-_panoramio.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Irbes_ligzda_pie_Vecdorvalka,_Dundagas_pagasts,_Dundagas_novads,_Latvia_-_panoramio.jpg', encoding: 'image/jpeg', depictIDs: 'Q93189;Q2274832;Q4785;Q211', depictLabels: 'egg;Dundaga Municipality;nest;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M76489113', fileLabel: 'Map of Valka County with borders of estates and parishes', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Map_of_Valka_County_(colored,_parish_and_estate_borders)_(1904).jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Map_of_Valka_County_(colored,_parish_and_estate_borders)_(1904).jpg', encoding: 'image/jpeg', depictIDs: 'Q102496;Q3739156;Q4006;Q211', depictLabels: 'parish;Valka Parish;map;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M92455552', fileLabel: 'M92455552', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Skaista_sala_ezerā.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Skaista_sala_ezerā.jpg', encoding: 'image/jpeg', creator: 'Karlisjm', depictIDs: 'Q133128;Q157624;Q1681353;Q2703478;Q17376042;Q211', depictLabels: 'Pinus sylvestris;Betula pubescens;bog;mirror image;Cenas tīrelis;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M92747231', fileLabel: 'M92747231', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Priedes_cena.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Priedes_cena.jpg', encoding: 'image/jpeg', creator: 'Karlisjm', depictIDs: 'Q133128;Q503021;Q1681353;Q15069452;Q27487235;Q527;Q756;Q7722;Q10884;Q211;Q37477', depictLabels: 'Pinus sylvestris;Natura 2000;bog;Natura 2000 protected area;Q27487235;sky;plant;morning;tree;Latvia;fog',
}, {
  file: 'https://commons.wikimedia.org/entity/M56967779', fileLabel: 'M56967779', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/TEC-2_2007.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/TEC-2_2007.jpg', encoding: 'image/jpeg', depictIDs: 'Q159719;Q170477;Q211', depictLabels: 'power station;chimney;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M92747950', fileLabel: 'M92747950', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Barkavas_ozolu_audze.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Barkavas_ozolu_audze.jpg', encoding: 'image/jpeg', creator: 'Karlisjm', depictIDs: 'Q165145;Q503021;Q2884591;Q10965030;Q211', depictLabels: 'Quercus robur;Natura 2000;Barkava Parish;Barkavas ozolu audze;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M79057694', fileLabel: 'Rocky seashore of Vidzeme', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Saulriets,_Vidzemes_Akmeņainā_jūrmala.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Saulriets,_Vidzemes_Akmeņainā_jūrmala.jpg', encoding: 'image/jpeg', creator: 'Avejolus', depictIDs: 'Q166564;Q211', depictLabels: 'sunset;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M56289578', fileLabel: 'M56289578', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Liepaja_-_panoramio_(25).jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Liepaja_-_panoramio_(25).jpg', encoding: 'image/jpeg', depictIDs: 'Q167668;Q146;Q211', depictLabels: 'Liepāja;house cat;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M91702776', fileLabel: 'Riga technical university', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Riga_Technical_University_at_night_on_the_lower_left.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Riga_Technical_University_at_night_on_the_lower_left.jpg', encoding: 'image/jpeg', depictIDs: 'Q200250;Q411895;Q702492;Q575;Q1773;Q9128;Q211;Q41176', depictLabels: 'metropolis;Riga Technical University;urban area;night;Riga;light;Latvia;building',
}, {
  file: 'https://commons.wikimedia.org/entity/M43593382', fileLabel: 'M43593382', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Stokholmas_iela_44-46.JPG200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Stokholmas_iela_44-46.JPG', encoding: 'image/jpeg', creator: 'AcidiX', depictIDs: 'Q210272;Q4989906;Q211', depictLabels: 'cultural heritage;monument;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M73220697', fileLabel: 'M73220697', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Meņģeļi._Brāļu_Jurjānu_dzimtās_mājas_20.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Meņģeļi._Brāļu_Jurjānu_dzimtās_mājas_20.jpg', encoding: 'image/jpeg', creator: 'VardeCe', depictIDs: 'Q210272;Q4989906;Q211', depictLabels: 'cultural heritage;monument;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M54140791', fileLabel: 'M54140791', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Drabeši_parish,_Latvia_-_panoramio_(2).jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Drabeši_parish,_Latvia_-_panoramio_(2).jpg', encoding: 'image/jpeg', depictIDs: 'Q221722;Q211', depictLabels: 'bike path;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M91039680', fileLabel: 'Murjāņu sporta ģimnāzijas stadions', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Murjāņu_sporta_ģimnāzijas_stadions_2.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Murjāņu_sporta_ģimnāzijas_stadions_2.jpg', encoding: 'image/jpeg', creator: 'Gimnazists123', depictIDs: 'Q483110;Q349;Q211', depictLabels: 'stadium;sport;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M79057697', fileLabel: 'Rocky seashore of Vidzeme', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Vidzemes_akmeņains_jūras_krasts.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Vidzemes_akmeņains_jūras_krasts.jpg', encoding: 'image/jpeg', creator: 'Avejolus', depictIDs: 'Q745303;Q211', depictLabels: 'Vidzeme;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M90180683', fileLabel: 'M90180683', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/P121_krogsetas.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/P121_krogsetas.jpg', encoding: 'image/jpeg', creator: 'Kpsk parlaments', depictIDs: 'Q1049667;Q211;Q34442', depictLabels: 'road surface;Latvia;road',
}, {
  file: 'https://commons.wikimedia.org/entity/M67988177', fileLabel: 'M67988177', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Latvian_Independence_Day_military_parade_(26169124564).jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Latvian_Independence_Day_military_parade_(26169124564).jpg', encoding: 'image/jpeg', depictIDs: 'Q1184840;Q13156702;Q211', depictLabels: 'military vehicle;military tattoo;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M88540117', fileLabel: 'M88540117', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/COVID_Confirmed_Cases_Latvia.png200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/COVID_Confirmed_Cases_Latvia.png', encoding: 'image/png', creator: 'Maskaravivek', depictIDs: 'Q1474611;Q81068910;Q211;Q42848', depictLabels: 'plot;COVID-19 pandemic;Latvia;data',
}, {
  file: 'https://commons.wikimedia.org/entity/M57781107', fileLabel: 'M57781107', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Medumi_Parish,_Latvia_-_panoramio_(23).jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Medumi_Parish,_Latvia_-_panoramio_(23).jpg', encoding: 'image/jpeg', depictIDs: 'Q2615106;Q211', depictLabels: 'Medumi Parish;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M91039681', fileLabel: 'Urdziņas upīte Murjāņos', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Urdziņas_upīte.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Urdziņas_upīte.jpg', encoding: 'image/jpeg', creator: 'Gimnazists123', depictIDs: 'Q15219402;Q55659167;Q4022;Q211', depictLabels: 'Murjāņi;natural watercourse;river;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M30915858', fileLabel: 'M30915858', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/18th_November_Torchlight_procession_2013_from_St_Peter’s_Church.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/18th_November_Torchlight_procession_2013_from_St_Peter’s_Church.jpg', encoding: 'image/jpeg', creator: 'Statistiķis', depictIDs: 'Q26693326;Q1773;Q211', depictLabels: 'Torchlight Procession;Riga;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M68932511', fileLabel: 'M68932511', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Saeimas_namā_sveic_Latvijas_olimpiešus_un_paralimpiešus_(41051345385).jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Saeimas_namā_sveic_Latvijas_olimpiešus_un_paralimpiešus_(41051345385).jpg', encoding: 'image/jpeg', depictIDs: 'Q5389;Q25291;Q211', depictLabels: 'Olympic Games;2018;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M43710881', fileLabel: 'M43710881', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Jelgavas_Pils_rudenī.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Jelgavas_Pils_rudenī.jpg', encoding: 'image/jpeg', creator: 'Vinbergv', depictIDs: 'Q16560;Q211', depictLabels: 'palace;Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M51346871', fileLabel: 'M51346871', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/16-08-30-Riga_Daugavgrīva-RR2_3781.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/16-08-30-Riga_Daugavgrīva-RR2_3781.jpg', encoding: 'image/jpeg', depictIDs: 'Q211', depictLabels: 'Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M57949307', fileLabel: 'M57949307', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Baltā_stārķa_ligzda_Nr.2362,_Krapes_pagasts,_Ogres_novads,_Latvia_-_panoramio.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Baltā_stārķa_ligzda_Nr.2362,_Krapes_pagasts,_Ogres_novads,_Latvia_-_panoramio.jpg', encoding: 'image/jpeg', depictIDs: 'Q211', depictLabels: 'Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M69504755', fileLabel: 'M69504755', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/DPP_1993.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/DPP_1993.jpg', encoding: 'image/jpeg', creator: 'Normunds Kolby', depictIDs: 'Q211', depictLabels: 'Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M72526934', fileLabel: 'M72526934', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Jelgavas_Svētās_Trīsvienības_baznīcas_tornis_04.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Jelgavas_Svētās_Trīsvienības_baznīcas_tornis_04.jpg', encoding: 'image/jpeg', creator: 'Edgars2007', depictIDs: 'Q211', depictLabels: 'Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M79057700', fileLabel: 'Rocky seashore of Vidzeme', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Akmeņainā_jūrmala.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Akmeņainā_jūrmala.jpg', encoding: 'image/jpeg', creator: 'Avejolus', depictIDs: 'Q211', depictLabels: 'Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M79057699', fileLabel: 'Rocky seashore of Vidzeme', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Vakars_Vidzemes_akmeņainā_jūrmalā.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Vakars_Vidzemes_akmeņainā_jūrmalā.jpg', encoding: 'image/jpeg', creator: 'Avejolus', depictIDs: 'Q211', depictLabels: 'Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M85647724', fileLabel: 'Logo of the ministry of the education and culture of the republic of Latvia', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Лого_Минобрнауки_Латвии.png200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Лого_Минобрнауки_Латвии.png', encoding: 'image/png', creator: 'Igors Cernovs', depictIDs: 'Q211', depictLabels: 'Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M88064176', fileLabel: 'M88064176', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/COVID-19_Outbreak_Cases_in_Latvia.jpg200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/COVID-19_Outbreak_Cases_in_Latvia.jpg', encoding: 'image/jpeg', creator: 'Mirashhh', depictIDs: 'Q211', depictLabels: 'Latvia',
}, {
  file: 'https://commons.wikimedia.org/entity/M88216687', fileLabel: 'Cases of COVID-19 in Latvia by region', thumb: 'http://commons.wikimedia.org/wiki/Special:FilePath/Cases_of_COVID-19_in_Latvia_by_region.png200', fileOrig: 'http://commons.wikimedia.org/wiki/Special:FilePath/Cases_of_COVID-19_in_Latvia_by_region.png', encoding: 'image/png', creator: 'LV1000', depictIDs: 'Q211', depictLabels: 'Latvia',
}];
